import ConfigItem from "./ConfigItem.js";
import ConfigContainer from "./ConfigContainer.js";
export default class ConfigFactory {
    static createDefaultConfigContainer(): ConfigContainer;
    static createLineWidthConfig(): ConfigItem;
    static createColorConfig(): ConfigItem;
    static createOpacityConfig(): ConfigItem;
    static createContourConfig(): ConfigItem;
    static createRoundCapConfig(): ConfigItem;
    static createTouchesPerTickConfig(): ConfigItem;
    static createBrushAreaDiameterConfig(): ConfigItem;
    static createBrushAreaWidthConfig(): ConfigItem;
    static createBrushAreaHeightConfig(): ConfigItem;
    static createElementDiameterConfig(): ConfigItem;
    static createElementWidthConfig(): ConfigItem;
    static createElementHeightConfig(): ConfigItem;
    static createBrushAreaRotationConfig(): ConfigItem;
    static createElementRotationConfig(): ConfigItem;
    static createElementEdgesCountConfig(): ConfigItem;
    static createElementRandomRedColorSpreadConfig(): ConfigItem;
    static createElementRandomGreenColorSpreadConfig(): ConfigItem;
    static createElementRandomBlueColorSpreadConfig(): ConfigItem;
    static createElementRandomDiameterSpreadConfig(): ConfigItem;
    static createElementDistanceFromClickConfig(): ConfigItem;
    static createElementLapsPerSecondConfig(): ConfigItem;
    static createGumElasticityConfig(): ConfigItem;
    static createStripedLineConfig(): ConfigItem;
    static createStripeLineLengthConfig(): ConfigItem;
    static createStripeGapLengthConfig(): ConfigItem;
    static createLineWidthFunctionConfig(): ConfigItem;
    static createColorFunctionEnabledConfig(): ConfigItem;
    static createRedValueFunctionConfig(): ConfigItem;
    static createGreenValueFunctionConfig(): ConfigItem;
    static createBlueValueFunctionConfig(): ConfigItem;
    static createOpacityFunctionConfig(): ConfigItem;
    static createElementDiameterFunctionConfig(): ConfigItem;
}
